-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS users (
  id bigint primary key generated by default as identity,
  email citext not null unique,
  password_hash text,
  created_at timestamp(0) not null default (now() at time  zone 'utc'),
  updated_at timestamp(0) not null default (now() at time  zone 'utc')
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS users;
-- +goose StatementEnd
