@baseUrl=http://suindara.dev:3000/api/v1

POST {{baseUrl}}/users/register HTTP/1.1
content-type: application/json
accept: application/json

{
  "firstName": "joão",
  "lastName": "tester",
  "email": "suintest@email.com",
  "password": "123@123a"
}

###

POST {{baseUrl}}/users/login HTTP/1.1
content-type: application/json
accept: application/json

{
  "email": "suintest@email.com",
  "password": "123@123a"
}

###

